
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package GXML;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int width = 34;
  public static final int multO = 18;
  public static final int keyC = 66;
  public static final int Aend = 30;
  public static final int txtO = 8;
  public static final int plus = 57;
  public static final int bold = 41;
  public static final int buttO = 20;
  public static final int Ainit = 29;
  public static final int winC = 5;
  public static final int video = 52;
  public static final int impO = 2;
  public static final int txtarea = 45;
  public static final int letter = 69;
  public static final int multC = 19;
  public static final int HEXA = 43;
  public static final int txtC = 9;
  public static final int img = 53;
  public static final int coma = 56;
  public static final int buttC = 21;
  public static final int impC = 3;
  public static final int act = 49;
  public static final int defO = 16;
  public static final int first = 26;
  public static final int ctrlO = 10;
  public static final int border = 35;
  public static final int defC = 17;
  public static final int cer = 63;
  public static final int ctrlC = 11;
  public static final int equal = 67;
  public static final int apos = 64;
  public static final int italic = 42;
  public static final int max = 47;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int dataO = 14;
  public static final int second = 27;
  public static final int color = 28;
  public static final int listO = 12;
  public static final int mini = 48;
  public static final int por = 58;
  public static final int desp = 46;
  public static final int dataC = 15;
  public static final int posY = 32;
  public static final int nome = 38;
  public static final int listC = 13;
  public static final int posX = 31;
  public static final int abi = 62;
  public static final int id = 24;
  public static final int falso = 37;
  public static final int contaiO = 6;
  public static final int gion = 59;
  public static final int tipo = 25;
  public static final int refe = 50;
  public static final int tam = 40;
  public static final int verdad = 36;
  public static final int sendO = 22;
  public static final int path = 54;
  public static final int numeric = 44;
  public static final int high = 33;
  public static final int parC = 61;
  public static final int contaiC = 7;
  public static final int parA = 60;
  public static final int nro = 68;
  public static final int font = 39;
  public static final int keyO = 65;
  public static final int autoplay = 55;
  public static final int sendC = 23;
  public static final int musica = 51;
  public static final int winO = 4;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "impO",
  "impC",
  "winO",
  "winC",
  "contaiO",
  "contaiC",
  "txtO",
  "txtC",
  "ctrlO",
  "ctrlC",
  "listO",
  "listC",
  "dataO",
  "dataC",
  "defO",
  "defC",
  "multO",
  "multC",
  "buttO",
  "buttC",
  "sendO",
  "sendC",
  "id",
  "tipo",
  "first",
  "second",
  "color",
  "Ainit",
  "Aend",
  "posX",
  "posY",
  "high",
  "width",
  "border",
  "verdad",
  "falso",
  "nome",
  "font",
  "tam",
  "bold",
  "italic",
  "HEXA",
  "numeric",
  "txtarea",
  "desp",
  "max",
  "mini",
  "act",
  "refe",
  "musica",
  "video",
  "img",
  "path",
  "autoplay",
  "coma",
  "plus",
  "por",
  "gion",
  "parA",
  "parC",
  "abi",
  "cer",
  "apos",
  "keyO",
  "keyC",
  "equal",
  "nro",
  "letter"
  };
}

